<?php
if ( ! defined( 'ABSPATH' ) ) exit;

global $wpdb;

$sql = '';
$table_countries = $wpdb->prefix . "wpja_countries";

$sql = "INSERT IGNORE INTO $table_countries VALUES (null, 'AF', 'Afghanistan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AL', 'Albania');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DZ', 'Algeria');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DS', 'American Samoa');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AD', 'Andorra');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AO', 'Angola');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AI', 'Anguilla');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AQ', 'Antarctica');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AG', 'Antigua and Barbuda');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AR', 'Argentina');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AM', 'Armenia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AW', 'Aruba');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AU', 'Australia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AT', 'Austria');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AZ', 'Azerbaijan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BS', 'Bahamas');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BH', 'Bahrain');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BD', 'Bangladesh');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BB', 'Barbados');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BY', 'Belarus');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BE', 'Belgium');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BZ', 'Belize');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BJ', 'Benin');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BM', 'Bermuda');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BT', 'Bhutan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BO', 'Bolivia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BA', 'Bosnia and Herzegovina');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BW', 'Botswana');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BV', 'Bouvet Island');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BR', 'Brazil');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IO', 'British Indian Ocean Territory');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BN', 'Brunei Darussalam');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BG', 'Bulgaria');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BF', 'Burkina Faso');
        INSERT IGNORE INTO $table_countries VALUES (null, 'BI', 'Burundi');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KH', 'Cambodia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CM', 'Cameroon');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CA', 'Canada');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CV', 'Cape Verde');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KY', 'Cayman Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CF', 'Central African Republic');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TD', 'Chad');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CL', 'Chile');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CN', 'China');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CX', 'Christmas Island');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CC', 'Cocos (Keeling) Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CO', 'Colombia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KM', 'Comoros');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CG', 'Congo');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CK', 'Cook Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CR', 'Costa Rica');
        INSERT IGNORE INTO $table_countries VALUES (null, 'HR', 'Croatia (Hrvatska)');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CU', 'Cuba');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CY', 'Cyprus');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CZ', 'Czech Republic');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DK', 'Denmark');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DJ', 'Djibouti');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DM', 'Dominica');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DO', 'Dominican Republic');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TP', 'East Timor');
        INSERT IGNORE INTO $table_countries VALUES (null, 'EC', 'Ecuador');
        INSERT IGNORE INTO $table_countries VALUES (null, 'EG', 'Egypt');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SV', 'El Salvador');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GQ', 'Equatorial Guinea');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ER', 'Eritrea');
        INSERT IGNORE INTO $table_countries VALUES (null, 'EE', 'Estonia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ET', 'Ethiopia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FK', 'Falkland Islands (Malvinas)');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FO', 'Faroe Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FJ', 'Fiji');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FI', 'Finland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FR', 'France');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FX', 'France, Metropolitan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GF', 'French Guiana');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PF', 'French Polynesia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TF', 'French Southern Territories');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GA', 'Gabon');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GM', 'Gambia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GE', 'Georgia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'DE', 'Germany');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GH', 'Ghana');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GI', 'Gibraltar');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GK', 'Guernsey');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GR', 'Greece');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GL', 'Greenland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GD', 'Grenada');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GP', 'Guadeloupe');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GU', 'Guam');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GT', 'Guatemala');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GN', 'Guinea');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GW', 'Guinea-Bissau');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GY', 'Guyana');
        INSERT IGNORE INTO $table_countries VALUES (null, 'HT', 'Haiti');
        INSERT IGNORE INTO $table_countries VALUES (null, 'HM', 'Heard and Mc Donald Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'HN', 'Honduras');
        INSERT IGNORE INTO $table_countries VALUES (null, 'HK', 'Hong Kong');
        INSERT IGNORE INTO $table_countries VALUES (null, 'HU', 'Hungary');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IS', 'Iceland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IN', 'India');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IM', 'Isle of Man');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ID', 'Indonesia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IR', 'Iran');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IQ', 'Iraq');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IE', 'Ireland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IL', 'Israel');
        INSERT IGNORE INTO $table_countries VALUES (null, 'IT', 'Italy');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CI', 'Ivory Coast');
        INSERT IGNORE INTO $table_countries VALUES (null, 'JE', 'Jersey');
        INSERT IGNORE INTO $table_countries VALUES (null, 'JM', 'Jamaica');
        INSERT IGNORE INTO $table_countries VALUES (null, 'JP', 'Japan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'JO', 'Jordan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KZ', 'Kazakhstan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KE', 'Kenya');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KI', 'Kiribati');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KP', 'North Korea');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KR', 'South Korea');
        INSERT IGNORE INTO $table_countries VALUES (null, 'XK', 'Kosovo');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KW', 'Kuwait');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KG', 'Kyrgyzstan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LA', 'Lao Peoples Democratic Republic');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LV', 'Latvia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LB', 'Lebanon');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LS', 'Lesotho');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LR', 'Liberia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LY', 'Libyan Arab Jamahiriya');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LI', 'Liechtenstein');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LT', 'Lithuania');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LU', 'Luxembourg');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MO', 'Macau');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MK', 'Macedonia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MG', 'Madagascar');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MW', 'Malawi');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MY', 'Malaysia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MV', 'Maldives');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ML', 'Mali');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MT', 'Malta');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MH', 'Marshall Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MQ', 'Martinique');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MR', 'Mauritania');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MU', 'Mauritius');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TY', 'Mayotte');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MX', 'Mexico');
        INSERT IGNORE INTO $table_countries VALUES (null, 'FM', 'Micronesia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MD', 'Moldova');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MC', 'Monaco');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MN', 'Mongolia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ME', 'Montenegro');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MS', 'Montserrat');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MA', 'Morocco');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MZ', 'Mozambique');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MM', 'Myanmar');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NA', 'Namibia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NR', 'Nauru');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NP', 'Nepal');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NL', 'Netherlands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AN', 'Netherlands Antilles');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NC', 'New Caledonia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NZ', 'New Zealand');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NI', 'Nicaragua');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NE', 'Niger');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NG', 'Nigeria');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NU', 'Niue');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NF', 'Norfolk Island');
        INSERT IGNORE INTO $table_countries VALUES (null, 'MP', 'Northern Mariana Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'NO', 'Norway');
        INSERT IGNORE INTO $table_countries VALUES (null, 'OM', 'Oman');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PK', 'Pakistan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PW', 'Palau');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PS', 'Palestine');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PA', 'Panama');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PG', 'Papua New Guinea');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PY', 'Paraguay');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PE', 'Peru');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PH', 'Philippines');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PN', 'Pitcairn');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PL', 'Poland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PT', 'Portugal');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PR', 'Puerto Rico');
        INSERT IGNORE INTO $table_countries VALUES (null, 'QA', 'Qatar');
        INSERT IGNORE INTO $table_countries VALUES (null, 'RE', 'Reunion');
        INSERT IGNORE INTO $table_countries VALUES (null, 'RO', 'Romania');
        INSERT IGNORE INTO $table_countries VALUES (null, 'RU', 'Russian Federation');
        INSERT IGNORE INTO $table_countries VALUES (null, 'RW', 'Rwanda');
        INSERT IGNORE INTO $table_countries VALUES (null, 'KN', 'Saint Kitts and Nevis');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LC', 'Saint Lucia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VC', 'Saint Vincent and the Grenadines');
        INSERT IGNORE INTO $table_countries VALUES (null, 'WS', 'Samoa');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SM', 'San Marino');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ST', 'Sao Tome and Principe');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SA', 'Saudi Arabia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SN', 'Senegal');
        INSERT IGNORE INTO $table_countries VALUES (null, 'RS', 'Serbia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SC', 'Seychelles');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SL', 'Sierra Leone');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SG', 'Singapore');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SK', 'Slovakia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SI', 'Slovenia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SB', 'Solomon Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SO', 'Somalia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ZA', 'South Africa');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GS', 'South Georgia South Sandwich Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SS', 'South Sudan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ES', 'Spain');
        INSERT IGNORE INTO $table_countries VALUES (null, 'LK', 'Sri Lanka');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SH', 'St. Helena');
        INSERT IGNORE INTO $table_countries VALUES (null, 'PM', 'St. Pierre and Miquelon');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SD', 'Sudan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SR', 'Suriname');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SZ', 'Swaziland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SE', 'Sweden');
        INSERT IGNORE INTO $table_countries VALUES (null, 'CH', 'Switzerland');
        INSERT IGNORE INTO $table_countries VALUES (null, 'SY', 'Syrian Arab Republic');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TW', 'Taiwan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TJ', 'Tajikistan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TZ', 'Tanzania');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TH', 'Thailand');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TG', 'Togo');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TK', 'Tokelau');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TO', 'Tonga');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TT', 'Trinidad and Tobago');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TN', 'Tunisia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TR', 'Turkey');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TM', 'Turkmenistan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TC', 'Turks and Caicos Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'TV', 'Tuvalu');
        INSERT IGNORE INTO $table_countries VALUES (null, 'UG', 'Uganda');
        INSERT IGNORE INTO $table_countries VALUES (null, 'UA', 'Ukraine');
        INSERT IGNORE INTO $table_countries VALUES (null, 'AE', 'United Arab Emirates');
        INSERT IGNORE INTO $table_countries VALUES (null, 'GB', 'United Kingdom');
        INSERT IGNORE INTO $table_countries VALUES (null, 'US', 'United States');
        INSERT IGNORE INTO $table_countries VALUES (null, 'UM', 'United States outlying islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'UY', 'Uruguay');
        INSERT IGNORE INTO $table_countries VALUES (null, 'UZ', 'Uzbekistan');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VU', 'Vanuatu');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VA', 'Vatican City State');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VE', 'Venezuela');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VN', 'Vietnam');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VG', 'Virgin Islands (British)');
        INSERT IGNORE INTO $table_countries VALUES (null, 'VI', 'Virgin Islands (U.S.)');
        INSERT IGNORE INTO $table_countries VALUES (null, 'WF', 'Wallis and Futuna Islands');
        INSERT IGNORE INTO $table_countries VALUES (null, 'EH', 'Western Sahara');
        INSERT IGNORE INTO $table_countries VALUES (null, 'YE', 'Yemen');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ZR', 'Zaire');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ZM', 'Zambia');
        INSERT IGNORE INTO $table_countries VALUES (null, 'ZW', 'Zimbabwe');";

wpja_execute_multiline_sql($sql);

$sql = '';

$table_education_levels = $wpdb->prefix . "wpja_education_levels";

$sql = "INSERT IGNORE INTO $table_education_levels VALUES (null, 'Early childhood Education');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Early childhood Education (Pre-primary education)');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Primary education');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Lower secondary education');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Upper secondary education');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Certificate');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Diploma');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Post-secondary non-tertiary education');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Short-cycle tertiary education');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Bachelor or equivalent');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Master or equivalent');
        INSERT IGNORE INTO $table_education_levels VALUES (null, 'Doctoral or equivalent');";

wpja_execute_multiline_sql($sql);

$sql = '';

$table_driving_licences = $wpdb->prefix . "wpja_driving_licences";

$sql = "INSERT IGNORE INTO $table_driving_licences VALUES (null, 'AM');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'A1');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'A2');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'A');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'B');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'BE');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'B1');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'C1');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'C1E');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'C');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'CE');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'D1');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'D1E');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'D');
        INSERT IGNORE INTO $table_driving_licences VALUES (null, 'DE');";

wpja_execute_multiline_sql($sql);

$sql = "";

$table_job_types = $wpdb->prefix . "wpja_job_types";

$sql = "INSERT IGNORE INTO $table_job_types VALUES (null, 'First Jobs');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Jobs for 14- and 15-Year-Olds');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Jobs for High School Students');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Part-Time Jobs for College Students');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Jobs for College Graduates');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Jobs Abroad for College Graduates');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Part-Time Jobs');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Temp-to-Perm Jobs');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Internships');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Seasonal Jobs');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Summer Jobs');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Summer Jobs for Kids');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Summer Jobs for Teachers');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Jobs for Parents');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Work-at-Home Jobs');
        INSERT IGNORE INTO $table_job_types VALUES (null, 'Work-at-Home Data Entry Jobs');";

wpja_execute_multiline_sql($sql);

function wpja_execute_multiline_sql($sql)
{
    global $wpdb;
    $sqlParts = array_filter(explode(";", $sql));
    foreach($sqlParts as $part)
    {
        $wpdb->query($part);
        if($wpdb->last_error != '')
        {
            $error = new WP_Error("dberror", __("Database query error"), $wpdb->last_error);
            $wpdb->query("rollback;");
            return $error;
        }
    }
    $sqlParts = '';
    return true;
}